#-------------------------------
# General Site Settings

title: Lina Johansson
description: Good ideas never go out of style
email: lina@lingonberrys.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Skills, url: '/index.html#about-me'}
- {name: Work, url: '/index.html#work'}
- {name: Contact, url: '#contact'}
- {name: About, url: '/about/index.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Lingonberry Studio is the portfolio site and creative stylings done by Lina Johansson.'
  rel-author: 'http://twitter.com/linalingonberry'
  rel-publisher: 'http://twitter.com/linalingonberry'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# Skills Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  In my years as a designer I have wrangled color, and tamed type – even the most stubborn kerning. I have zipped, scored, and mocked. No publication is safe from my style sheets, photo retouching, and prepress skills. No website is impervious to my extraordinary CSS and HTML code. I translate invisible ideas into tangible objects, and frame language into pictures. I am a dreamer, and a doer. I am a designer.

resume: >
  We can also kick it old school if you like and download my <a href="/assets/img/Lina.Johansson.pdf">resume</a>.

skills:
- {name: Visual Design, value: '9'}
- {name: Creative Direction, value: '8'}
- {name: Branding, value: '9'}
- {name: HTML/CSS, value: '5'}
- {name: UI Design, value: '8'}
- {name: Prototyping, value: '7'}
- {name: Print Design, value: '8'}
- {name: Illustration, value: '9'}
- {name: Elephant Trivia, value: '10'}

#-------------------------------
# Work Section

digital:
- {name: Affiliate Page Case Study, folder: 'proj-14', file: 'work/proj-14.html'}
- {name: DreamHost Rebrand, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: DreamHost Cloud Case Study, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: PlayDate App, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Astrology Artist Book, folder: 'proj-9', file: 'work/proj-9.html'}
- {name: Cartoon Network Annual Report, folder: 'proj-12', file: 'work/proj-12.html'}
- {name: Birthday Advent Calendar, folder: 'proj-15', file: 'work/proj-15.html'}
- {name: DIY Foldable Robot, folder: 'proj-16', file: 'work/proj-16.html'}



print:
- {name: Cartoon Network Annual Report, folder: 'proj-12', file: 'work/proj-12.html'}
- {name: Karlstad SFAI-Conference, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Astrology Artist Book, folder: 'proj-9', file: 'work/proj-9.html'}
- {name: Ingrid's Cupboard, folder: 'proj-10', file: 'work/proj-10.html'}
- {name: The Girl with Dragon Tattoo, folder: 'proj-11', file: 'work/proj-11.html'}
- {name: Vector Illustration, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Traditional Illustration, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Reach out & Touch You Tour, folder: 'proj-2', file: 'work/proj-2.html'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/linalingonberry'}
- {icon: 'instagram', link: 'https://www.instagram.com/Lingonberry'}
- {icon: 'behance', link: 'https://www.behance.net/Lingonberry'}
- {icon: 'facebook', link: 'https://www.facebook.com/Lingonberrydesign'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/johanssonlina'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

bio: 
  I was born in a tiny town outside of Göteborg Sweden, loving Abba, Volvo and IKEA like most other Swedes.
